"""Generate a small benchmark-language table with QQ."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from qq import Database

CODES = [
    "en",
    "fr",
    "de",
    "es",
    "pt",
    "it",
    "nl",
    "ru",
    "cmn",
    "ja",
    "ko",
    "arb",
    "hi",
    "bn",
    "ta",
    "te",
    "th",
    "vi",
    "id",
    "zsm",
    "swh",
    "yo",
    "ig",
    "ha",
    "am",
    "my",
    "km",
    "lo",
    "ka",
    "hy",
]


def tex(s: str | None) -> str:
    if not s:
        return "---"
    return s.replace("&", r"\&").replace("%", r"\%").replace("$", r"\$").replace("#", r"\#").replace("_", r"\_")


def speakers(n: int | None) -> str:
    if n is None:
        return "---"
    if n >= 1_000_000_000:
        return f"{n / 1_000_000_000:.1f}B"
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n / 1_000:.0f}K"
    return str(n)


def script(lang: Any) -> str:
    if lang.canonical_scripts:
        return lang.canonical_scripts[0].iso_15924
    return lang.script_codes[0] if lang.script_codes else "---"


def family(lang: Any) -> str:
    return lang.root_family.name if lang.root_family else "---"


def row(lang: Any) -> str:
    cells = [
        tex(lang.name),
        rf"\texttt{{{lang.bcp_47 or '---'}}}",
        rf"\texttt{{{lang.iso_639_3 or '---'}}}",
        script(lang),
        speakers(lang.speaker_count),
        tex(family(lang)),
    ]
    return " & ".join(cells) + r" \\"


def main() -> None:
    db = Database.load(names_path=None)
    rows = [row(db.get(code)) for code in CODES]

    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\begin{tabular}{lcccrl}",
        r"\toprule",
        r"Language & BCP-47 & ISO 639-3 & Script & Speakers & Family \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Language metadata table generated by the QQ reporting case study.}",
        r"\label{tab:lang-table}",
        r"\end{table}",
        "",
    ]

    out = Path(__file__).with_name("output")
    out.mkdir(exist_ok=True)
    (out / "benchmark_languages.tex").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
